/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ahmagh2e (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-stranding-cargo-79db2b621cf742b38ade266815c2365b
Title: Death Stranding Cargo
*/
import { useGLTF } from '@react-three/drei'
import BaseModel, { type BaseModelProps } from './BaseModel'

type LargeModelProps = BaseModelProps & {}

const LargeModel = (props: Omit<LargeModelProps, 'gltfPath'>) => (<BaseModel {...props} gltfPath="/largeCargo/scene.gltf" />)

useGLTF.preload('/largeCargo/scene.gltf')

export default LargeModel