/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ahmagh2e (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-stranding-cargo-79db2b621cf742b38ade266815c2365b
Title: Death Stranding Cargo
*/
import { useGLTF } from '@react-three/drei'
import BaseModel, { type BaseModelProps } from './BaseModel'

type ModelProps = BaseModelProps & {}

const Model = (props: Omit<ModelProps, 'gltfPath'>) => (<BaseModel {...props} gltfPath="/cargo/scene.gltf" />)

useGLTF.preload('/cargo/scene.gltf')

export default Model